### ISSUE TITLE
Using Multiple Images in UIScrollView

### ISSUE THREAD

**Issue by thihaaung6245** [evgenyneu/ios-imagescroll-swift#1]
If you don't mind,can you push image array that include multiple images in uiscrollview with Page Control.I m struck at this.

Thanks you.really love to learn your scrollview.Please help

**Comment by evgenyneu** [comment]
Hi, thanks for suggestion. I think it would be out of scope for this demo. The idea of the repository was to demonstrate how one can use auto layout to zoom and scroll just one image. Feel free to fork it and experiment with multiple images. I will be interested to see your results. Thanks.
