### ISSUE TITLE
How would I enable double-tap to zoom ?

### ISSUE THREAD

**Issue by leonardbonfils** [evgenyneu/ios-imagescroll-swift#4]
Title

**Comment by evgenyneu** [comment]
Hi, I would add a tap gesture recogniser and write some code that zooms in and out on two taps.

There multiples examples here that can get you started: http://stackoverflow.com/questions/3967971/how-to-zoom-in-out-photo-on-double-tap-in-the-iphone-wwdc-2010-104-photoscroll
